### ISSUE TITLE
OpenHab Cloud Docker Image Request

### ISSUE THREAD

**Issue by JonasMH** [openhab/openhab-cloud#171]
Hey, 

I'm in the process of setting up an openhab-cloud instance and having some problems that could be solved by having a prebuilt docker image. Had to install NPM, NodeJS & errors such as 'Cannot find module '../build/Debug/addon', and additionally I'm not really a fan having to build the solution on my server.

So a image on the OpenHab Docker hub would really be appreciated.

**Comment by marziman** [comment]
Hi @JonasMH ,

there is actually a docker image and you just need to run one command with docker-compose.
It is described in the Readme.

BR Mehmet

**Comment by JonasMH** [comment]
I saw that, but the issue is that to do so, you need to clone the entire development repository onto the machine server, then build the image. Where what i suggest is to put a pre-built image up on the Docker Hub, so in my docker-compose file i can just do the following, without pulling the repo:

```
version: '2.2'
services:
  openhabcloud:
    image: openhab/openhab-cloud
    volumes:
      - /var/openhab-cloud/cloud-conf:/opt/openhabcloud/conf
    networks:
      - ohcloud-network
    links:
      - mongodb
      - redis
    ports:
      - 3000:3000
    restart: always

```

**Comment by marziman** [comment]
Ok, got your point.
Will tackle this and get back to you here.

BR Mehmet

**Comment by JonasMH** [comment]
Great! Let me know if you need any help and I'll do my best :) 

- Jonas

**Comment by marziman** [comment]
Hi @JonasMH,

I will push soon some cool stuff for this one.
That will also make you happy :-)

BR Mehmet

**Comment by JonasMH** [comment]
Hi @marziman,

Saw some images got posted to the docker hub on the openhab profile. Tried setting the app-image up and it worked after redis and mongodb was also setup. Made it much easier to get openhab cloud up and running. :)

Thank you for you help and work.

**Comment by JonasMH** [comment]
Regarding custom configuration it possible to bind a single file like so instead of swithing to the local build.

```
  openhabcloud:
    image: "openhab/openhabcloud-app"
    volumes:
      - ./openhabcloud/config.json:/opt/openhabcloud/config.json
```
